// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"SRD_AutoUpdater","status":true,"description":"Allows developers to set up automatic updates to occur whenever a player plays the game.","parameters":{"Update Text URL":"https://raw.githubusercontent.com/SistineDisco/AutoUpdaterTest/master/Master.txt","Initial Version":"1.00","== Version Options ==":"","Draw Version":"true","Version Format":"v%1","Version Text X":"Graphics.boxWidth - textWidth - 8","Version Text Y":"Graphics.boxHeight - textHeight - 24","Version Text Font":"GameFont","Version Text Color":"#FFFFFF","Version Text Size":"28","Version Outline Size":"3","Version Italic":"true"}},
{"name":"YEP_ExternalLinks","status":true,"description":"v1.00 Link back to your home page through the title screen\nand also be able to link your players from within the game.","parameters":{"Home Page URL":"https://www.google.com/","Home Page Text":"Home Page","Popup Blocker Notice":"The link was blocked by a pop-up blocker."}}
];
